name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Ou sua versão preferida

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput    
    - name: Check for static files
      run: |
            if [ ! -d "staticfiles" ]; then
            echo "Static files directory does not exist."
            exit 1
            else
            echo "Static files directory exists."
            fi
    - name: Check for migrations
      run: |
        if [ -z "$(python manage.py showmigrations | grep '\[X\]')" ]; then
            echo "No migrations have been applied."
            exit 1
        else
            echo "Migrations have been applied."
        fi
    - name: Check for database
      run: |
            if [ ! -f "db.sqlite3" ]; then
                echo "Database file does not exist."
                exit 1
            else
                echo "Database file exists."
            fi
    - name: Check for media files
      run: |
        if [ ! -d "media" ]; then
            echo "Media files directory does not exist."
            exit 1
        else
            echo "Media files directory exists."
        fi